// ──────────────── COMPLETE LIST OF COUNTRIES AND US STATES FOR SEARCH ────────────────
window.allCountries = [
  // Europe
  { name: "Serbia", capital: "Belgrade", population: "6.9M", language: "Serbian", flag: "🇷🇸", continent: "Europe" },
  { name: "Germany", capital: "Berlin", population: "83M", language: "German", flag: "🇩🇪", continent: "Europe" },
  { name: "France", capital: "Paris", population: "68M", language: "French", flag: "🇫🇷", continent: "Europe" },
  { name: "Italy", capital: "Rome", population: "59M", language: "Italian", flag: "🇮🇹", continent: "Europe" },
  { name: "United Kingdom", capital: "London", population: "67M", language: "English", flag: "🇬🇧", continent: "Europe" },
  { name: "Spain", capital: "Madrid", population: "47M", language: "Spanish", flag: "🇪🇸", continent: "Europe" },
  { name: "Portugal", capital: "Lisbon", population: "10M", language: "Portuguese", flag: "🇵🇹", continent: "Europe" },
  { name: "Netherlands", capital: "Amsterdam", population: "17M", language: "Dutch", flag: "🇳🇱", continent: "Europe" },
  { name: "Belgium", capital: "Brussels", population: "11M", language: "Dutch/French/German", flag: "🇧🇪", continent: "Europe" },
  { name: "Switzerland", capital: "Bern", population: "8.7M", language: "German/French/Italian", flag: "🇨🇭", continent: "Europe" },
  { name: "Austria", capital: "Vienna", population: "9M", language: "German", flag: "🇦🇹", continent: "Europe" },
  { name: "Poland", capital: "Warsaw", population: "38M", language: "Polish", flag: "🇵🇱", continent: "Europe" },
  { name: "Czech Republic", capital: "Prague", population: "10.7M", language: "Czech", flag: "🇨🇿", continent: "Europe" },
  { name: "Sweden", capital: "Stockholm", population: "10.4M", language: "Swedish", flag: "🇸🇪", continent: "Europe" },
  { name: "Norway", capital: "Oslo", population: "5.4M", language: "Norwegian", flag: "🇳🇴", continent: "Europe" },
  { name: "Denmark", capital: "Copenhagen", population: "5.8M", language: "Danish", flag: "🇩🇰", continent: "Europe" },
  { name: "Finland", capital: "Helsinki", population: "5.5M", language: "Finnish/Swedish", flag: "🇫🇮", continent: "Europe" },
  { name: "Ireland", capital: "Dublin", population: "5M", language: "English/Irish", flag: "🇮🇪", continent: "Europe" },
  { name: "Greece", capital: "Athens", population: "10.4M", language: "Greek", flag: "🇬🇷", continent: "Europe" },
  { name: "Hungary", capital: "Budapest", population: "9.6M", language: "Hungarian", flag: "🇭🇺", continent: "Europe" },
  { name: "Romania", capital: "Bucharest", population: "19M", language: "Romanian", flag: "🇷🇴", continent: "Europe" },
  { name: "Bulgaria", capital: "Sofia", population: "6.9M", language: "Bulgarian", flag: "🇧🇬", continent: "Europe" },
  { name: "Croatia", capital: "Zagreb", population: "3.9M", language: "Croatian", flag: "🇭🇷", continent: "Europe" },
  { name: "Slovakia", capital: "Bratislava", population: "5.4M", language: "Slovak", flag: "🇸🇰", continent: "Europe" },
  { name: "Slovenia", capital: "Ljubljana", population: "2.1M", language: "Slovenian", flag: "🇸🇮", continent: "Europe" },
  // Africa (subset for brevity, you can extend)
  { name: "South Africa", capital: "Pretoria", population: "60M", language: "11 Official", flag: "🇿🇦", continent: "Africa" },
  { name: "Egypt", capital: "Cairo", population: "104M", language: "Arabic", flag: "🇪🇬", continent: "Africa" },
  { name: "Nigeria", capital: "Abuja", population: "218M", language: "English", flag: "🇳🇬", continent: "Africa" },
  { name: "Kenya", capital: "Nairobi", population: "55M", language: "Swahili/English", flag: "🇰🇪", continent: "Africa" },
  { name: "Morocco", capital: "Rabat", population: "37M", language: "Arabic/Berber", flag: "🇲🇦", continent: "Africa" },
  // Asia (subset)
  { name: "Japan", capital: "Tokyo", population: "125M", language: "Japanese", flag: "🇯🇵", continent: "Asia" },
  { name: "China", capital: "Beijing", population: "1.4B", language: "Chinese", flag: "🇨🇳", continent: "Asia" },
  { name: "India", capital: "New Delhi", population: "1.4B", language: "Hindi/English", flag: "🇮🇳", continent: "Asia" },
  { name: "South Korea", capital: "Seoul", population: "52M", language: "Korean", flag: "🇰🇷", continent: "Asia" },
  { name: "Thailand", capital: "Bangkok", population: "70M", language: "Thai", flag: "🇹🇭", continent: "Asia" },
  { name: "Vietnam", capital: "Hanoi", population: "99M", language: "Vietnamese", flag: "🇻🇳", continent: "Asia" },
  { name: "Indonesia", capital: "Jakarta", population: "277M", language: "Indonesian", flag: "🇮🇩", continent: "Asia" },
  { name: "Philippines", capital: "Manila", population: "115M", language: "Filipino/English", flag: "🇵🇭", continent: "Asia" },
  { name: "Turkey", capital: "Ankara", population: "85M", language: "Turkish", flag: "🇹🇷", continent: "Asia" },
  // North America (countries)
  { name: "Canada", capital: "Ottawa", population: "39M", language: "English/French", flag: "🇨🇦", continent: "North America" },
  { name: "Mexico", capital: "Mexico City", population: "129M", language: "Spanish", flag: "🇲🇽", continent: "North America" },
  // South America
  { name: "Brazil", capital: "Brasília", population: "214M", language: "Portuguese", flag: "🇧🇷", continent: "South America" },
  { name: "Argentina", capital: "Buenos Aires", population: "46M", language: "Spanish", flag: "🇦🇷", continent: "South America" },
  // Oceania
  { name: "Australia", capital: "Canberra", population: "26M", language: "English", flag: "🇦🇺", continent: "Oceania" },
  { name: "New Zealand", capital: "Wellington", population: "5M", language: "English/Māori", flag: "🇳🇿", continent: "Oceania" },
  // USA States (each as separate entry)
  { name: "USA-Alabama", capital: "Montgomery", population: "5M", language: "English", flag: "🇺🇸", continent: "North America" },
  { name: "USA-Alaska", capital: "Juneau", population: "0.7M", language: "English", flag: "🇺🇸", continent: "North America" },
  { name: "USA-Arizona", capital: "Phoenix", population: "7.4M", language: "English", flag: "🇺🇸", continent: "North America" },
  { name: "USA-Arkansas", capital: "Little Rock", population: "3M", language: "English", flag: "🇺🇸", continent: "North America" },
  { name: "USA-California", capital: "Sacramento", population: "39.5M", language: "English", flag: "🇺🇸", continent: "North America" },
  { name: "USA-Colorado", capital: "Denver", population: "5.8M", language: "English", flag: "🇺🇸", continent: "North America" },
  { name: "USA-Connecticut", capital: "Hartford", population: "3.6M", language: "English", flag: "🇺🇸", continent: "North America" },
  { name: "USA-Delaware", capital: "Dover", population: "1M", language: "English", flag: "🇺🇸", continent: "North America" },
  { name: "USA-Florida", capital: "Tallahassee", population: "22M", language: "English", flag: "🇺🇸", continent: "North America" },
  { name: "USA-Georgia", capital: "Atlanta", population: "10.9M", language: "English", flag: "🇺🇸", continent: "North America" },
  { name: "USA-Hawaii", capital: "Honolulu", population: "1.4M", language: "English/Hawaiian", flag: "🇺🇸", continent: "North America" },
  { name: "USA-Idaho", capital: "Boise", population: "1.9M", language: "English", flag: "🇺🇸", continent: "North America" },
  { name: "USA-Illinois", capital: "Springfield", population: "12.6M", language: "English", flag: "🇺🇸", continent: "North America" },
  { name: "USA-Indiana", capital: "Indianapolis", population: "6.8M", language: "English", flag: "🇺🇸", continent: "North America" },
  { name: "USA-Iowa", capital: "Des Moines", population: "3.2M", language: "English", flag: "🇺🇸", continent: "North America" },
  { name: "USA-Kansas", capital: "Topeka", population: "2.9M", language: "English", flag: "🇺🇸", continent: "North America" },
  { name: "USA-Kentucky", capital: "Frankfort", population: "4.5M", language: "English", flag: "🇺🇸", continent: "North America" },
  { name: "USA-Louisiana", capital: "Baton Rouge", population: "4.6M", language: "English", flag: "🇺🇸", continent: "North America" },
  { name: "USA-Maine", capital: "Augusta", population: "1.4M", language: "English", flag: "🇺🇸", continent: "North America" },
  { name: "USA-Maryland", capital: "Annapolis", population: "6.2M", language: "English", flag: "🇺🇸", continent: "North America" },
  { name: "USA-Massachusetts", capital: "Boston", population: "7M", language: "English", flag: "🇺🇸", continent: "North America" },
  { name: "USA-Michigan", capital: "Lansing", population: "10M", language: "English", flag: "🇺🇸", continent: "North America" },
  { name: "USA-Minnesota", capital: "Saint Paul", population: "5.7M", language: "English", flag: "🇺🇸", continent: "North America" },
  { name: "USA-Mississippi", capital: "Jackson", population: "2.9M", language: "English", flag: "🇺🇸", continent: "North America" },
  { name: "USA-Missouri", capital: "Jefferson City", population: "6.2M", language: "English", flag: "🇺🇸", continent: "North America" },
  { name: "USA-Montana", capital: "Helena", population: "1.1M", language: "English", flag: "🇺🇸", continent: "North America" },
  { name: "USA-Nebraska", capital: "Lincoln", population: "2M", language: "English", flag: "🇺🇸", continent: "North America" },
  { name: "USA-Nevada", capital: "Carson City", population: "3.2M", language: "English", flag: "🇺🇸", continent: "North America" },
  { name: "USA-New Hampshire", capital: "Concord", population: "1.4M", language: "English", flag: "🇺🇸", continent: "North America" },
  { name: "USA-New Jersey", capital: "Trenton", population: "9.3M", language: "English", flag: "🇺🇸", continent: "North America" },
  { name: "USA-New Mexico", capital: "Santa Fe", population: "2.1M", language: "English/Spanish", flag: "🇺🇸", continent: "North America" },
  { name: "USA-New York", capital: "Albany", population: "19.8M", language: "English", flag: "🇺🇸", continent: "North America" },
  { name: "USA-North Carolina", capital: "Raleigh", population: "10.7M", language: "English", flag: "🇺🇸", continent: "North America" },
  { name: "USA-North Dakota", capital: "Bismarck", population: "0.8M", language: "English", flag: "🇺🇸", continent: "North America" },
  { name: "USA-Ohio", capital: "Columbus", population: "11.8M", language: "English", flag: "🇺🇸", continent: "North America" },
  { name: "USA-Oklahoma", capital: "Oklahoma City", population: "4M", language: "English", flag: "🇺🇸", continent: "North America" },
  { name: "USA-Oregon", capital: "Salem", population: "4.2M", language: "English", flag: "🇺🇸", continent: "North America" },
  { name: "USA-Pennsylvania", capital: "Harrisburg", population: "13M", language: "English", flag: "🇺🇸", continent: "North America" },
  { name: "USA-Rhode Island", capital: "Providence", population: "1.1M", language: "English", flag: "🇺🇸", continent: "North America" },
  { name: "USA-South Carolina", capital: "Columbia", population: "5.2M", language: "English", flag: "🇺🇸", continent: "North America" },
  { name: "USA-South Dakota", capital: "Pierre", population: "0.9M", language: "English", flag: "🇺🇸", continent: "North America" },
  { name: "USA-Tennessee", capital: "Nashville", population: "7M", language: "English", flag: "🇺🇸", continent: "North America" },
  { name: "USA-Texas", capital: "Austin", population: "30M", language: "English", flag: "🇺🇸", continent: "North America" },
  { name: "USA-Utah", capital: "Salt Lake City", population: "3.4M", language: "English", flag: "🇺🇸", continent: "North America" },
  { name: "USA-Vermont", capital: "Montpelier", population: "0.6M", language: "English", flag: "🇺🇸", continent: "North America" },
  { name: "USA-Virginia", capital: "Richmond", population: "8.7M", language: "English", flag: "🇺🇸", continent: "North America" },
  { name: "USA-Washington", capital: "Olympia", population: "7.8M", language: "English", flag: "🇺🇸", continent: "North America" },
  { name: "USA-West Virginia", capital: "Charleston", population: "1.8M", language: "English", flag: "🇺🇸", continent: "North America" },
  { name: "USA-Wisconsin", capital: "Madison", population: "5.9M", language: "English", flag: "🇺🇸", continent: "North America" },
  { name: "USA-Wyoming", capital: "Cheyenne", population: "0.6M", language: "English", flag: "🇺🇸", continent: "North America" },
  // ─── MISSING COUNTRIES (UN members not in the original list) ───
{ name: "Afghanistan", capital: "Kabul", population: "41M", language: "Pashto/Dari", flag: "🇦🇫", continent: "Asia" },
{ name: "Albania", capital: "Tirana", population: "2.8M", language: "Albanian", flag: "🇦🇱", continent: "Europe" },
{ name: "Algeria", capital: "Algiers", population: "45M", language: "Arabic/Berber", flag: "🇩🇿", continent: "Africa" },
{ name: "Andorra", capital: "Andorra la Vella", population: "77k", language: "Catalan", flag: "🇦🇩", continent: "Europe" },
{ name: "Angola", capital: "Luanda", population: "35M", language: "Portuguese", flag: "🇦🇴", continent: "Africa" },
{ name: "Antigua and Barbuda", capital: "St. John's", population: "97k", language: "English", flag: "🇦🇬", continent: "North America" },
{ name: "Armenia", capital: "Yerevan", population: "3M", language: "Armenian", flag: "🇦🇲", continent: "Asia" },
{ name: "Azerbaijan", capital: "Baku", population: "10M", language: "Azerbaijani", flag: "🇦🇿", continent: "Asia" },
{ name: "Bahamas", capital: "Nassau", population: "400k", language: "English", flag: "🇧🇸", continent: "North America" },
{ name: "Bahrain", capital: "Manama", population: "1.8M", language: "Arabic", flag: "🇧🇭", continent: "Asia" },
{ name: "Bangladesh", capital: "Dhaka", population: "169M", language: "Bengali", flag: "🇧🇩", continent: "Asia" },
{ name: "Barbados", capital: "Bridgetown", population: "287k", language: "English", flag: "🇧🇧", continent: "North America" },
{ name: "Belarus", capital: "Minsk", population: "9.2M", language: "Belarusian/Russian", flag: "🇧🇾", continent: "Europe" },
{ name: "Belize", capital: "Belmopan", population: "400k", language: "English", flag: "🇧🇿", continent: "North America" },
{ name: "Benin", capital: "Porto-Novo", population: "14M", language: "French", flag: "🇧🇯", continent: "Africa" },
{ name: "Bhutan", capital: "Thimphu", population: "800k", language: "Dzongkha", flag: "🇧🇹", continent: "Asia" },
{ name: "Bolivia", capital: "Sucre", population: "12M", language: "Spanish", flag: "🇧🇴", continent: "South America" },
{ name: "Bosnia and Herzegovina", capital: "Sarajevo", population: "3.2M", language: "Bosnian/Croatian/Serbian", flag: "🇧🇦", continent: "Europe" },
{ name: "Botswana", capital: "Gaborone", population: "2.5M", language: "English/Tswana", flag: "🇧🇼", continent: "Africa" },
{ name: "Brunei", capital: "Bandar Seri Begawan", population: "450k", language: "Malay", flag: "🇧🇳", continent: "Asia" },
{ name: "Burkina Faso", capital: "Ouagadougou", population: "22M", language: "French", flag: "🇧🇫", continent: "Africa" },
{ name: "Burundi", capital: "Gitega", population: "13M", language: "Kirundi/French/English", flag: "🇧🇮", continent: "Africa" },
{ name: "Cabo Verde", capital: "Praia", population: "560k", language: "Portuguese", flag: "🇨🇻", continent: "Africa" },
{ name: "Cambodia", capital: "Phnom Penh", population: "17M", language: "Khmer", flag: "🇰🇭", continent: "Asia" },
{ name: "Cameroon", capital: "Yaoundé", population: "27M", language: "French/English", flag: "🇨🇲", continent: "Africa" },
{ name: "Central African Republic", capital: "Bangui", population: "5M", language: "French/Sango", flag: "🇨🇫", continent: "Africa" },
{ name: "Chad", capital: "N'Djamena", population: "18M", language: "French/Arabic", flag: "🇹🇩", continent: "Africa" },
{ name: "Chile", capital: "Santiago", population: "19M", language: "Spanish", flag: "🇨🇱", continent: "South America" },
{ name: "Colombia", capital: "Bogotá", population: "51M", language: "Spanish", flag: "🇨🇴", continent: "South America" },
{ name: "Comoros", capital: "Moroni", population: "900k", language: "Comorian/Arabic/French", flag: "🇰🇲", continent: "Africa" },
{ name: "Congo (DRC)", capital: "Kinshasa", population: "95M", language: "French", flag: "🇨🇩", continent: "Africa" },
{ name: "Congo (Republic)", capital: "Brazzaville", population: "5.5M", language: "French", flag: "🇨🇬", continent: "Africa" },
{ name: "Costa Rica", capital: "San José", population: "5.2M", language: "Spanish", flag: "🇨🇷", continent: "North America" },
{ name: "Cuba", capital: "Havana", population: "11M", language: "Spanish", flag: "🇨🇺", continent: "North America" },
{ name: "Cyprus", capital: "Nicosia", population: "1.2M", language: "Greek/Turkish", flag: "🇨🇾", continent: "Europe" },
{ name: "Djibouti", capital: "Djibouti", population: "1M", language: "Arabic/French", flag: "🇩🇯", continent: "Africa" },
{ name: "Dominica", capital: "Roseau", population: "72k", language: "English", flag: "🇩🇲", continent: "North America" },
{ name: "Dominican Republic", capital: "Santo Domingo", population: "11M", language: "Spanish", flag: "🇩🇴", continent: "North America" },
{ name: "Ecuador", capital: "Quito", population: "18M", language: "Spanish", flag: "🇪🇨", continent: "South America" },
{ name: "El Salvador", capital: "San Salvador", population: "6.3M", language: "Spanish", flag: "🇸🇻", continent: "North America" },
{ name: "Equatorial Guinea", capital: "Malabo", population: "1.5M", language: "Spanish/French/Portuguese", flag: "🇬🇶", continent: "Africa" },
{ name: "Eritrea", capital: "Asmara", population: "3.6M", language: "Tigrinya/Arabic/English", flag: "🇪🇷", continent: "Africa" },
{ name: "Estonia", capital: "Tallinn", population: "1.3M", language: "Estonian", flag: "🇪🇪", continent: "Europe" },
{ name: "Eswatini", capital: "Mbabane", population: "1.2M", language: "English/Swazi", flag: "🇸🇿", continent: "Africa" },
{ name: "Ethiopia", capital: "Addis Ababa", population: "120M", language: "Amharic", flag: "🇪🇹", continent: "Africa" },
{ name: "Fiji", capital: "Suva", population: "900k", language: "English/Fijian/Hindi", flag: "🇫🇯", continent: "Oceania" },
{ name: "Gabon", capital: "Libreville", population: "2.2M", language: "French", flag: "🇬🇦", continent: "Africa" },
{ name: "Gambia", capital: "Banjul", population: "2.7M", language: "English", flag: "🇬🇲", continent: "Africa" },
{ name: "Georgia", capital: "Tbilisi", population: "3.7M", language: "Georgian", flag: "🇬🇪", continent: "Asia" },
{ name: "Ghana", capital: "Accra", population: "34M", language: "English", flag: "🇬🇭", continent: "Africa" },
{ name: "Grenada", capital: "St. George's", population: "125k", language: "English", flag: "🇬🇩", continent: "North America" },
{ name: "Guatemala", capital: "Guatemala City", population: "17M", language: "Spanish", flag: "🇬🇹", continent: "North America" },
{ name: "Guinea", capital: "Conakry", population: "14M", language: "French", flag: "🇬🇳", continent: "Africa" },
{ name: "Guinea-Bissau", capital: "Bissau", population: "2M", language: "Portuguese", flag: "🇬🇼", continent: "Africa" },
{ name: "Guyana", capital: "Georgetown", population: "800k", language: "English", flag: "🇬🇾", continent: "South America" },
{ name: "Haiti", capital: "Port-au-Prince", population: "11M", language: "French/Creole", flag: "🇭🇹", continent: "North America" },
{ name: "Honduras", capital: "Tegucigalpa", population: "10M", language: "Spanish", flag: "🇭🇳", continent: "North America" },
{ name: "Iceland", capital: "Reykjavík", population: "375k", language: "Icelandic", flag: "🇮🇸", continent: "Europe" },
{ name: "Iran", capital: "Tehran", population: "88M", language: "Persian", flag: "🇮🇷", continent: "Asia" },
{ name: "Iraq", capital: "Baghdad", population: "45M", language: "Arabic/Kurdish", flag: "🇮🇶", continent: "Asia" },
{ name: "Israel", capital: "Jerusalem", population: "9.2M", language: "Hebrew/Arabic", flag: "🇮🇱", continent: "Asia" },
{ name: "Jamaica", capital: "Kingston", population: "2.8M", language: "English", flag: "🇯🇲", continent: "North America" },
{ name: "Jordan", capital: "Amman", population: "11M", language: "Arabic", flag: "🇯🇴", continent: "Asia" },
{ name: "Kazakhstan", capital: "Nur-Sultan", population: "19M", language: "Kazakh/Russian", flag: "🇰🇿", continent: "Asia" },
{ name: "Kiribati", capital: "South Tarawa", population: "130k", language: "English/I-Kiribati", flag: "🇰🇮", continent: "Oceania" },
{ name: "Kuwait", capital: "Kuwait City", population: "4.3M", language: "Arabic", flag: "🇰🇼", continent: "Asia" },
{ name: "Kyrgyzstan", capital: "Bishkek", population: "6.7M", language: "Kyrgyz/Russian", flag: "🇰🇬", continent: "Asia" },
{ name: "Laos", capital: "Vientiane", population: "7.5M", language: "Lao", flag: "🇱🇦", continent: "Asia" },
{ name: "Latvia", capital: "Riga", population: "1.8M", language: "Latvian", flag: "🇱🇻", continent: "Europe" },
{ name: "Lebanon", capital: "Beirut", population: "5.5M", language: "Arabic", flag: "🇱🇧", continent: "Asia" },
{ name: "Lesotho", capital: "Maseru", population: "2.3M", language: "English/Sesotho", flag: "🇱🇸", continent: "Africa" },
{ name: "Liberia", capital: "Monrovia", population: "5.4M", language: "English", flag: "🇱🇷", continent: "Africa" },
{ name: "Libya", capital: "Tripoli", population: "7M", language: "Arabic", flag: "🇱🇾", continent: "Africa" },
{ name: "Liechtenstein", capital: "Vaduz", population: "39k", language: "German", flag: "🇱🇮", continent: "Europe" },
{ name: "Lithuania", capital: "Vilnius", population: "2.7M", language: "Lithuanian", flag: "🇱🇹", continent: "Europe" },
{ name: "Luxembourg", capital: "Luxembourg", population: "650k", language: "Luxembourgish/French/German", flag: "🇱🇺", continent: "Europe" },
{ name: "Madagascar", capital: "Antananarivo", population: "30M", language: "Malagasy/French", flag: "🇲🇬", continent: "Africa" },
{ name: "Malawi", capital: "Lilongwe", population: "21M", language: "English/Chichewa", flag: "🇲🇼", continent: "Africa" },
{ name: "Malaysia", capital: "Kuala Lumpur", population: "33M", language: "Malay", flag: "🇲🇾", continent: "Asia" },
{ name: "Maldives", capital: "Malé", population: "520k", language: "Dhivehi", flag: "🇲🇻", continent: "Asia" },
{ name: "Mali", capital: "Bamako", population: "23M", language: "French", flag: "🇲🇱", continent: "Africa" },
{ name: "Malta", capital: "Valletta", population: "520k", language: "Maltese/English", flag: "🇲🇹", continent: "Europe" },
{ name: "Marshall Islands", capital: "Majuro", population: "42k", language: "Marshallese/English", flag: "🇲🇭", continent: "Oceania" },
{ name: "Mauritania", capital: "Nouakchott", population: "4.9M", language: "Arabic", flag: "🇲🇷", continent: "Africa" },
{ name: "Mauritius", capital: "Port Louis", population: "1.3M", language: "English/French/Creole", flag: "🇲🇺", continent: "Africa" },
{ name: "Micronesia", capital: "Palikir", population: "115k", language: "English", flag: "🇫🇲", continent: "Oceania" },
{ name: "Moldova", capital: "Chișinău", population: "2.6M", language: "Romanian", flag: "🇲🇩", continent: "Europe" },
{ name: "Monaco", capital: "Monaco", population: "39k", language: "French", flag: "🇲🇨", continent: "Europe" },
{ name: "Mongolia", capital: "Ulaanbaatar", population: "3.3M", language: "Mongolian", flag: "🇲🇳", continent: "Asia" },
{ name: "Montenegro", capital: "Podgorica", population: "0.6M", language: "Montenegrin", flag: "🇲🇪", continent: "Europe" },
{ name: "Mozambique", capital: "Maputo", population: "33M", language: "Portuguese", flag: "🇲🇿", continent: "Africa" },
{ name: "Myanmar", capital: "Naypyidaw", population: "54M", language: "Burmese", flag: "🇲🇲", continent: "Asia" },
{ name: "Namibia", capital: "Windhoek", population: "2.6M", language: "English", flag: "🇳🇦", continent: "Africa" },
{ name: "Nauru", capital: "Yaren", population: "10k", language: "Nauruan/English", flag: "🇳🇷", continent: "Oceania" },
{ name: "Nepal", capital: "Kathmandu", population: "30M", language: "Nepali", flag: "🇳🇵", continent: "Asia" },
{ name: "Nicaragua", capital: "Managua", population: "6.8M", language: "Spanish", flag: "🇳🇮", continent: "North America" },
{ name: "Niger", capital: "Niamey", population: "27M", language: "French", flag: "🇳🇪", continent: "Africa" },
{ name: "North Macedonia", capital: "Skopje", population: "2.1M", language: "Macedonian", flag: "🇲🇰", continent: "Europe" },
{ name: "Oman", capital: "Muscat", population: "4.6M", language: "Arabic", flag: "🇴🇲", continent: "Asia" },
{ name: "Pakistan", capital: "Islamabad", population: "240M", language: "Urdu/English", flag: "🇵🇰", continent: "Asia" },
{ name: "Palau", capital: "Ngerulmud", population: "18k", language: "Palauan/English", flag: "🇵🇼", continent: "Oceania" },
{ name: "Panama", capital: "Panama City", population: "4.5M", language: "Spanish", flag: "🇵🇦", continent: "North America" },
{ name: "Papua New Guinea", capital: "Port Moresby", population: "10M", language: "English/Tok Pisin/Hiri Motu", flag: "🇵🇬", continent: "Oceania" },
{ name: "Paraguay", capital: "Asunción", population: "6.8M", language: "Spanish/Guarani", flag: "🇵🇾", continent: "South America" },
{ name: "Peru", capital: "Lima", population: "33M", language: "Spanish", flag: "🇵🇪", continent: "South America" },
{ name: "Qatar", capital: "Doha", population: "2.9M", language: "Arabic", flag: "🇶🇦", continent: "Asia" },
{ name: "Russia", capital: "Moscow", population: "144M", language: "Russian", flag: "🇷🇺", continent: "Europe" },
{ name: "Rwanda", capital: "Kigali", population: "13M", language: "Kinyarwanda/English/French", flag: "🇷🇼", continent: "Africa" },
{ name: "Saint Kitts and Nevis", capital: "Basseterre", population: "47k", language: "English", flag: "🇰🇳", continent: "North America" },
{ name: "Saint Lucia", capital: "Castries", population: "180k", language: "English", flag: "🇱🇨", continent: "North America" },
{ name: "Saint Vincent and the Grenadines", capital: "Kingstown", population: "110k", language: "English", flag: "🇻🇨", continent: "North America" },
{ name: "Samoa", capital: "Apia", population: "220k", language: "Samoan/English", flag: "🇼🇸", continent: "Oceania" },
{ name: "San Marino", capital: "San Marino", population: "34k", language: "Italian", flag: "🇸🇲", continent: "Europe" },
{ name: "Sao Tome and Principe", capital: "São Tomé", population: "230k", language: "Portuguese", flag: "🇸🇹", continent: "Africa" },
{ name: "Saudi Arabia", capital: "Riyadh", population: "36M", language: "Arabic", flag: "🇸🇦", continent: "Asia" },
{ name: "Senegal", capital: "Dakar", population: "18M", language: "French", flag: "🇸🇳", continent: "Africa" },
{ name: "Seychelles", capital: "Victoria", population: "100k", language: "English/French/Seychellois Creole", flag: "🇸🇨", continent: "Africa" },
{ name: "Sierra Leone", capital: "Freetown", population: "8.5M", language: "English", flag: "🇸🇱", continent: "Africa" },
{ name: "Singapore", capital: "Singapore", population: "5.6M", language: "English/Malay/Chinese/Tamil", flag: "🇸🇬", continent: "Asia" },
{ name: "Solomon Islands", capital: "Honiara", population: "720k", language: "English", flag: "🇸🇧", continent: "Oceania" },
{ name: "Somalia", capital: "Mogadishu", population: "17M", language: "Somali/Arabic", flag: "🇸🇴", continent: "Africa" },
{ name: "South Sudan", capital: "Juba", population: "11M", language: "English", flag: "🇸🇸", continent: "Africa" },
{ name: "Sri Lanka", capital: "Colombo", population: "22M", language: "Sinhala/Tamil", flag: "🇱🇰", continent: "Asia" },
{ name: "Sudan", capital: "Khartoum", population: "48M", language: "Arabic/English", flag: "🇸🇩", continent: "Africa" },
{ name: "Suriname", capital: "Paramaribo", population: "620k", language: "Dutch", flag: "🇸🇷", continent: "South America" },
{ name: "Syria", capital: "Damascus", population: "22M", language: "Arabic", flag: "🇸🇾", continent: "Asia" },
{ name: "Tajikistan", capital: "Dushanbe", population: "10M", language: "Tajik", flag: "🇹🇯", continent: "Asia" },
{ name: "Tanzania", capital: "Dodoma", population: "65M", language: "Swahili/English", flag: "🇹🇿", continent: "Africa" },
{ name: "Timor-Leste", capital: "Dili", population: "1.4M", language: "Tetum/Portuguese", flag: "🇹🇱", continent: "Asia" },
{ name: "Togo", capital: "Lomé", population: "9M", language: "French", flag: "🇹🇬", continent: "Africa" },
{ name: "Tonga", capital: "Nuku'alofa", population: "100k", language: "Tongan/English", flag: "🇹🇴", continent: "Oceania" },
{ name: "Trinidad and Tobago", capital: "Port of Spain", population: "1.5M", language: "English", flag: "🇹🇹", continent: "North America" },
{ name: "Tunisia", capital: "Tunis", population: "12M", language: "Arabic", flag: "🇹🇳", continent: "Africa" },
{ name: "Turkmenistan", capital: "Ashgabat", population: "6M", language: "Turkmen", flag: "🇹🇲", continent: "Asia" },
{ name: "Tuvalu", capital: "Funafuti", population: "11k", language: "Tuvaluan/English", flag: "🇹🇻", continent: "Oceania" },
{ name: "Uganda", capital: "Kampala", population: "48M", language: "Swahili/English", flag: "🇺🇬", continent: "Africa" },
{ name: "Ukraine", capital: "Kyiv", population: "41M", language: "Ukrainian", flag: "🇺🇦", continent: "Europe" },
{ name: "United Arab Emirates", capital: "Abu Dhabi", population: "10M", language: "Arabic", flag: "🇦🇪", continent: "Asia" },
{ name: "United States", capital: "Washington D.C.", population: "333M", language: "English", flag: "🇺🇸", continent: "North America" },
{ name: "Uruguay", capital: "Montevideo", population: "3.4M", language: "Spanish", flag: "🇺🇾", continent: "South America" },
{ name: "Uzbekistan", capital: "Tashkent", population: "35M", language: "Uzbek", flag: "🇺🇿", continent: "Asia" },
{ name: "Vanuatu", capital: "Port Vila", population: "330k", language: "Bislama/English/French", flag: "🇻🇺", continent: "Oceania" },
{ name: "Venezuela", capital: "Caracas", population: "28M", language: "Spanish", flag: "🇻🇪", continent: "South America" },
{ name: "Yemen", capital: "Sana'a", population: "34M", language: "Arabic", flag: "🇾🇪", continent: "Asia" },
{ name: "Zambia", capital: "Lusaka", population: "20M", language: "English", flag: "🇿🇲", continent: "Africa" },
{ name: "Zimbabwe", capital: "Harare", population: "16M", language: "English", flag: "🇿🇼", continent: "Africa" },
  // You can add many more countries... this is a starter list.
  // Full list would contain ~193 UN members + 50 states = 243 entries.
  // I've included the structure so you can easily copy-paste missing ones.
];

// ──────────────── POLYGONS FOR COLLECTED TERRITORIES (green overlay) ────────────────
window.allPolygons = {
  "Serbia": [
    [ [20.0, 44.5], [19.5, 44.8], [19.0, 44.0], [19.5, 43.5], [20.5, 43.0], [21.5, 43.0], [22.0, 43.5], [22.5, 44.0], [22.0, 44.8], [21.5, 45.2], [20.5, 45.2], [20.0, 44.5] ]
  ],
  "Germany": [
    [ [6.0, 47.5], [7.0, 47.5], [8.0, 48.0], [9.0, 48.2], [10.0, 48.0], [11.0, 48.5], [12.0, 48.5], [13.0, 48.0], [14.0, 48.0], [15.0, 47.5], [15.0, 47.0], [14.5, 46.5], [13.5, 46.5], [12.5, 46.5], [11.5, 46.0], [10.5, 46.0], [9.5, 46.5], [8.5, 46.5], [7.5, 46.5], [6.5, 47.0], [6.0, 47.5] ]
  ],
  "Japan": [
    [ [130.0, 32.0], [131.0, 33.0], [132.0, 34.0], [133.0, 35.0], [134.0, 35.5], [135.0, 35.5], [136.0, 36.0], [137.0, 36.5], [138.0, 37.0], [139.0, 38.0], [140.0, 39.0], [141.0, 40.0], [142.0, 41.0], [143.0, 42.0], [144.0, 43.0], [145.0, 44.0], [145.5, 44.5], [145.0, 45.0], [144.0, 44.5], [143.0, 44.0], [142.0, 43.0], [141.0, 42.0], [140.0, 41.0], [139.0, 40.0], [138.0, 39.0], [137.0, 38.0], [136.0, 37.0], [135.0, 36.5], [134.0, 36.0], [133.0, 35.0], [132.0, 34.0], [131.0, 33.0], [130.0, 32.0] ]
  ],
  "USA-California": [
    [ [-124.4, 42.0], [-124.0, 41.5], [-123.5, 40.5], [-123.0, 40.0], [-122.5, 39.5], [-121.5, 39.0], [-120.5, 39.0], [-120.0, 38.5], [-119.5, 38.0], [-119.0, 37.5], [-118.5, 37.0], [-118.0, 36.5], [-117.5, 36.0], [-117.0, 35.5], [-116.5, 35.0], [-116.0, 34.5], [-115.5, 34.0], [-115.0, 33.5], [-114.5, 33.0], [-114.0, 32.5], [-114.5, 32.0], [-115.5, 32.0], [-116.5, 32.5], [-117.0, 33.0], [-117.5, 33.5], [-118.0, 34.0], [-118.5, 34.5], [-119.0, 35.0], [-119.5, 35.5], [-120.0, 36.0], [-120.5, 36.5], [-121.0, 37.0], [-121.5, 37.5], [-122.0, 38.0], [-122.5, 38.5], [-123.0, 39.0], [-123.5, 39.5], [-124.0, 40.0], [-124.4, 40.5], [-124.4, 42.0] ]
  ]
};
